#!/usr/bin/env python3
"""Generates Ratatoskr/Auth/StringPrepTables.cs from RFC 3454.

The tables in RFC 3454 are normative and long - together about nine hundred
ranges. Copied by hand, a typo in there would be practically impossible to
find: it only shows up once a particular character appears in a password, and
then as a login that fails for no reason.

Hence this route. The generator loads the RFC text, reads the ranges and writes
the C# file. Whoever doubts the tables lets it run and compares.

    python3 tools/stringprep/generate.py

Without arguments the RFC is fetched from rfc-editor.org; with a path as the
first argument it is read from a local copy.
"""

import re
import sys
import urllib.request
from pathlib import Path

RFC_URL = "https://www.rfc-editor.org/rfc/rfc3454.txt"

# table name -> (C# field name, comment)
TABLES = {
    "A.1":   ("Unassigned",        "A.1: Unassigned in Unicode 3.2"),
    "B.1":   ("MappedToNothing",   "B.1: Falls away without replacement during mapping"),
    "C.1.2": ("NonAsciiSpace",     "C.1.2: Space characters outside of ASCII"),
    "C.2.1": ("AsciiControl",      "C.2.1: ASCII control characters"),
    "C.2.2": ("NonAsciiControl",   "C.2.2: Control characters outside of ASCII"),
    "C.3":   ("PrivateUse",        "C.3: Private use"),
    "C.4":   ("NonCharacter",      "C.4: Non-characters"),
    "C.5":   ("Surrogate",         "C.5: Surrogates"),
    "C.6":   ("InappropriateForPlainText",
              "C.6: Inappropriate for plain text"),
    "C.7":   ("InappropriateForCanonical",
              "C.7: Inappropriate for canonical representation"),
    "C.8":   ("DisplayOrDeprecated",
              "C.8: Change the display or are deprecated"),
    "C.9":   ("Tagging",           "C.9: Tagging characters"),
    "D.1":   ("RandALCat",         "D.1: Bidirectional category R or AL"),
    "D.2":   ("LCat",              "D.2: Bidirectional category L"),
}

HEADER = """/*
 * Copyright (c) 2010-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of Ratatoskr <https://www.github.com/Vanaheimr/Ratatoskr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace org.GraphDefined.Vanaheimr.Ratatoskr;

/// <summary>
/// The tables from RFC 3454 (StringPrep) that SASLprep builds upon.
/// </summary>
/// <remarks>
/// <b>Generated by tools/stringprep/generate.py - do not edit by hand.</b>
///
/// Every table stands there as a flat sequence of range bounds: at an even
/// position the first, at an odd one the last code point of the range, sorted
/// ascending. The lookup is binary.
///
/// The tables are frozen at Unicode 3.2 - that is not sloppiness but the whole
/// point: whoever treats a password containing a later assigned character
/// differently than the peer does no longer gets in. StringPrep therefore
/// freezes the character repertoire.
/// </remarks>
internal static class StringPrepTables
{

    #region Contains(Table, CodePoint)

    /// <summary>Does the code point lie within one of the ranges of this table?</summary>
    public static Boolean Contains(UInt32[] Table, UInt32 CodePoint)
    {

        var low   = 0;
        var high  = Table.Length / 2 - 1;

        while (low <= high)
        {

            var mid = (low + high) / 2;

            if      (CodePoint < Table[mid * 2])      high  = mid - 1;
            else if (CodePoint > Table[mid * 2 + 1])  low   = mid + 1;
            else                                      return true;

        }

        return false;

    }

    #endregion

"""


def load(source):
    if source:
        return Path(source).read_text(encoding="utf-8").splitlines()
    with urllib.request.urlopen(RFC_URL) as response:
        return response.read().decode("utf-8").splitlines()


def ranges(lines, name):
    """The ranges of a table, sorted ascending and merged."""

    start = lines.index(f"   ----- Start Table {name} -----")
    end   = lines.index(f"   ----- End Table {name} -----")

    found = []

    for line in lines[start + 1:end]:

        line = line.strip()

        # page breaks of the RFC text
        if not line or "Hoffman" in line or line.startswith("RFC 3454"):
            continue

        match = re.match(r"^([0-9A-F]{4,6})(?:-([0-9A-F]{4,6}))?\s*(?:;|$)", line)

        if not match:
            raise SystemExit(f"table {name}: line not understood {line!r}")

        first = int(match.group(1), 16)
        last  = int(match.group(2) or match.group(1), 16)

        found.append((first, last))

    found.sort()

    # Merge adjacent ranges - that makes the table shorter and does not make
    # the binary search wrong.
    merged = []

    for first, last in found:
        if merged and first <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], last))
        else:
            merged.append((first, last))

    return merged


def emit(name, field, comment, values):

    out = [f"    /// <summary>{comment} ({len(values)} ranges).</summary>",
           f"    public static readonly UInt32[] {field} = ["]

    line = "       "

    for first, last in values:
        piece = f" 0x{first:04X}, 0x{last:04X},"
        if len(line) + len(piece) > 96:
            out.append(line)
            line = "       "
        line += piece

    out.append(line)
    out.append("    ];")
    out.append("")

    return out


def main():

    lines = load(sys.argv[1] if len(sys.argv) > 1 else None)

    body = []

    for name, (field, comment) in TABLES.items():
        body.extend(emit(name, field, comment, ranges(lines, name)))

    target = Path(__file__).resolve().parents[2] / "Ratatoskr" / "Auth" / "StringPrepTables.cs"

    text = HEADER + "\n".join(body) + "}\n"

    target.write_bytes(b"\xef\xbb\xbf" + text.replace("\n", "\r\n").encode("utf-8"))

    print(f"{target} written")


if __name__ == "__main__":
    main()
