#!/usr/bin/env python3
"""Generates Ratatoskr/Common/BidiClasses.cs from the Unicode file DerivedBidiClass.txt.

The bidi rule from RFC 5893 asks, for every code point of a label, for its
Bidi_Class property. .NET does not provide it, and it cannot be derived from
anything else either: whether a letter is R, AL or L depends on its script, not
on its category.

Transcribed by hand the table could not be checked - there are over a thousand
ranges. Hence this route: the generator downloads the Unicode file, reads the
ranges and writes the C# file. Whoever doubts the table lets it run and
compares.

    python3 tools/unicode/generate-bidiclass.py

Without arguments the file is fetched from unicode.org; with a path as the first
argument it is read from a local copy.

Class L is not written out. It is the largest and at the same time the default:
whatever is in none of the other tables is L. For the bidi rule that suffices,
because everything arriving here is an assigned code point - the unassigned ones
were sorted out by the IDNA ladder beforehand.
"""

import re
import sys
import urllib.request
from pathlib import Path

VERSION = "15.1.0"
URL     = f"https://www.unicode.org/Public/{VERSION}/ucd/extracted/DerivedBidiClass.txt"

# Bidi_Class -> (C# field name, comment). L is missing on purpose (see above).
CLASSES = {
    "R":    ("R",    "Right-to-left (Hebrew and related scripts)"),
    "AL":   ("AL",   "Right-to-left Arabic"),
    "AN":   ("AN",   "Arabic digits"),
    "EN":   ("EN",   "European digits"),
    "ES":   ("ES",   "European separators (plus, minus)"),
    "CS":   ("CS",   "Common separators (comma, full stop, colon)"),
    "ET":   ("ET",   "European terminators (currency, per cent)"),
    "ON":   ("ON",   "Other neutral characters"),
    "BN":   ("BN",   "No effect on the direction of run"),
    "NSM":  ("NSM",  "Non-spacing characters (combining marks)"),
}

HEADER = """/*
 * Copyright (c) 2010-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of Ratatoskr <https://www.github.com/Vanaheimr/Ratatoskr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace org.GraphDefined.Vanaheimr.Ratatoskr;

/// <summary>
/// The bidi class of a code point (Unicode %VERSION%, DerivedBidiClass.txt).
/// </summary>
public enum BidiClass
{
    L,
    R,
    AL,
    AN,
    EN,
    ES,
    CS,
    ET,
    ON,
    BN,
    NSM
}

/// <summary>
/// The table of bidi classes the bidi rule from RFC 5893 rests on.
/// </summary>
/// <remarks>
/// <b>Generated by tools/unicode/generate-bidiclass.py - do not edit by
/// hand.</b>
///
/// Every class sits there as a flat sequence of range bounds: at an even
/// position the first, at an odd one the last code point of the range, sorted
/// ascending. The search is binary.
///
/// <b>L is not written out</b>, it is the default: whatever is in none of the
/// other tables is L. That is not a shortcut but the way the Unicode file itself
/// is built - and it saves the largest table of them all.
/// </remarks>
internal static class BidiClasses
{

    #region ClassOf(CodePoint)

    /// <summary>The bidi class of this code point.</summary>
    public static BidiClass ClassOf(UInt32 CodePoint)
    {

        if (Contains(R,   CodePoint))  return BidiClass.R;
        if (Contains(AL,  CodePoint))  return BidiClass.AL;
        if (Contains(AN,  CodePoint))  return BidiClass.AN;
        if (Contains(EN,  CodePoint))  return BidiClass.EN;
        if (Contains(ES,  CodePoint))  return BidiClass.ES;
        if (Contains(CS,  CodePoint))  return BidiClass.CS;
        if (Contains(ET,  CodePoint))  return BidiClass.ET;
        if (Contains(ON,  CodePoint))  return BidiClass.ON;
        if (Contains(BN,  CodePoint))  return BidiClass.BN;
        if (Contains(NSM, CodePoint))  return BidiClass.NSM;

        return BidiClass.L;

    }

    #endregion

    #region (private) Contains(Table, CodePoint)

    /// <summary>Does the code point lie in one of this table's ranges?</summary>
    private static Boolean Contains(UInt32[] Table, UInt32 CodePoint)
    {

        var low   = 0;
        var high  = Table.Length / 2 - 1;

        while (low <= high)
        {

            var mid = (low + high) / 2;

            if      (CodePoint < Table[mid * 2])      high  = mid - 1;
            else if (CodePoint > Table[mid * 2 + 1])  low   = mid + 1;
            else                                      return true;

        }

        return false;

    }

    #endregion

"""


def load(source):
    if source:
        return Path(source).read_text(encoding="utf-8").splitlines()
    with urllib.request.urlopen(URL) as response:
        return response.read().decode("utf-8").splitlines()


def ranges(lines, name):
    """The ranges of one bidi class, sorted ascending and merged.

    Lines with '@missing' describe the default values for unassigned code
    points. They stay out of it: what is unassigned does not occur in a label
    anyway - the IDNA ladder rejects it beforehand.
    """

    found = []

    for line in lines:

        line = line.split("#", 1)[0].strip()

        if not line or line.startswith("@"):
            continue

        match = re.match(r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*(\w+)\s*$", line)

        if not match:
            raise SystemExit(f"unintelligible line {line!r}")

        if match.group(3) != name:
            continue

        first = int(match.group(1), 16)
        last  = int(match.group(2) or match.group(1), 16)

        found.append((first, last))

    if not found:
        raise SystemExit(f"class {name}: not a single range found")

    found.sort()

    merged = []

    for first, last in found:
        if merged and first <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], last))
        else:
            merged.append((first, last))

    return merged


def emit(field, comment, values):

    out = [f"    /// <summary>{comment} ({len(values)} ranges).</summary>",
           f"    internal static readonly UInt32[] {field} = ["]

    line = "       "

    for first, last in values:
        piece = f" 0x{first:04X}, 0x{last:04X},"
        if len(line) + len(piece) > 96:
            out.append(line)
            line = "       "
        line += piece

    out.append(line)
    out.append("    ];")
    out.append("")

    return out


def main():

    lines = load(sys.argv[1] if len(sys.argv) > 1 else None)

    body = []

    for name, (field, comment) in CLASSES.items():
        body.extend(emit(field, comment, ranges(lines, name)))

    target = Path(__file__).resolve().parents[2] / "Ratatoskr" / "Common" / "BidiClasses.cs"

    text = HEADER.replace("%VERSION%", VERSION) + "\n".join(body) + "}\n"

    target.write_bytes(b"\xef\xbb\xbf" + text.replace("\n", "\r\n").encode("utf-8"))

    print(f"{target} written")


if __name__ == "__main__":
    main()
