#!/usr/bin/env python3
"""Generates Ratatoskr/Common/ContextTables.cs for the rules from RFC 5892, appendix A.

The seven rules A.1 to A.7 ask for three properties .NET does not ship:

    Canonical_Combining_Class == 9 (virama)   for A.1 and A.2
    Joining_Type                              for A.1
    Script                                    for A.4 to A.7

They cannot be derived - whether a letter belongs to the Greek or to the Hebrew
script is in no category. So the same route as with the bidi classes: fetch it
from the Unicode database, do not guess.

    python3 tools/unicode/generate-contexttables.py

Without arguments the files are fetched from unicode.org.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import ucd

VERSION = "15.1.0"
BASE    = f"https://www.unicode.org/Public/{VERSION}/ucd"

CCC_URL      = f"{BASE}/extracted/DerivedCombiningClass.txt"
JOINING_URL  = f"{BASE}/extracted/DerivedJoiningType.txt"
SCRIPTS_URL  = f"{BASE}/Scripts.txt"

HEADER = f"""
namespace org.GraphDefined.Vanaheimr.Ratatoskr;

/// <summary>
/// The Unicode properties the contextual rules from RFC 5892, appendix A rest
/// on (Unicode {VERSION}).
/// </summary>
/// <remarks>
/// <b>Generated by tools/unicode/generate-contexttables.py - do not edit by
/// hand.</b>
///
/// Only what the seven rules need is written out: the virama characters
/// (combining class 9), the four Joining_Type values that occur in A.1, and five
/// scripts. A complete script table would be several times larger and would
/// answer nothing that is asked here.
/// </remarks>
internal static class ContextTables
{{

    #region Contains(Table, CodePoint)

    /// <summary>Does the code point lie in one of this table's ranges?</summary>
    internal static Boolean Contains(UInt32[] Table, UInt32 CodePoint)
    {{

        var low   = 0;
        var high  = Table.Length / 2 - 1;

        while (low <= high)
        {{

            var mid = (low + high) / 2;

            if      (CodePoint < Table[mid * 2])      high  = mid - 1;
            else if (CodePoint > Table[mid * 2 + 1])  low   = mid + 1;
            else                                      return true;

        }}

        return false;

    }}

    #endregion

"""


def main():

    body = []

    ccc = ucd.load(CCC_URL)
    body.extend(ucd.emit("Virama", "Combining class 9 - the virama characters",
                         ucd.ranges(ccc, "9")))

    joining = ucd.load(JOINING_URL)

    for value, comment in (("L", "Joining_Type L (left-joining)"),
                           ("D", "Joining_Type D (dual-joining)"),
                           ("R", "Joining_Type R (right-joining)"),
                           ("T", "Joining_Type T (transparent - marks and format characters)")):
        body.extend(ucd.emit(f"Joining{value}", comment, ucd.ranges(joining, value)))

    scripts = ucd.load(SCRIPTS_URL)

    for value, comment in (("Greek",    "Script Greek (A.4)"),
                           ("Hebrew",   "Script Hebrew (A.5 and A.6)"),
                           ("Hiragana", "Script Hiragana (A.7)"),
                           ("Katakana", "Script Katakana (A.7)"),
                           ("Han",      "Script Han (A.7)")):
        body.extend(ucd.emit(f"Script{value}", comment, ucd.ranges(scripts, value)))

    target = Path(__file__).resolve().parents[2] / "Ratatoskr" / "Common" / "ContextTables.cs"

    ucd.write(target, ucd.LICENSE_HEADER + HEADER + "\n".join(body) + "}\n")


if __name__ == "__main__":
    main()
